### ISSUE TITLE
update lazymc to support 1.18

### ISSUE THREAD

**Issue by ventoryprod** [timvisee/lazymc#17]

**Comment by timvisee** [comment]
I've just released `0.2.7` with Minecraft 1.18.1 support.

You may still use the previous version. Adjusting the Minecraft version in the `lazymc.toml` file should be fine, see [here](https://github.com/timvisee/lazymc/blob/master/docs/protocol-version.md).

Note that this doesn't support Minecraft 1.18 in lazymc lobby mode yet. I'll try to implement that at a later time.
