### ISSUE TITLE
proxy does not work properly on 1.18.1

### ISSUE THREAD

**Issue by ventoryprod** [timvisee/lazymc#18]
The server was moved to 1.18.1, and it loaded and worked fine, but it does not allow the player to enter the server:kicks me with server is loading message (kick method)
disabled proxy in lazymc.toml, and it fixed
maybe I missed something again. Please check how it works for you.

lazymc v0.2.7
purpur server 1.18.1 #1434
1.0.0 proxy companion-plugin
server on Windows 11

**Comment by timvisee** [comment]
You probably need to update the companion plugin to the latest version to support Minecraft 1.18. The server console likely shows an error when SpigotProxy tries to start.

I asked the developer to release the latest JAR [here](https://github.com/riku6460/SpigotProxy/issues/5).

I compiled the latest plugin for you here in the mean time: https://send.vis.ee/download/d99bc609b1d576ee/#CgSL0ozfE0kYdu8zjIJTLA

You'll likely have to update this plugin with every new major Minecraft version. If no new version is available, you may temporarily set the `server.send_proxy_v2` property to `false`.
