### ISSUE TITLE
Add option to exit

### ISSUE THREAD

**Issue by megabyte6** [timvisee/lazymc#19]
Hi, I was wondering if adding a "stop" command would be possible because I'm able to start lazymc but I haven't found a way yet to stop the executable without manually killing the process.
If there already is a way to do this please let me know. Thank you! 🙂

**Comment by timvisee** [comment]
Using CTRL+C (SIGINT) should work. If the server is currently active, it will stop the server first. When it is sleeping you can CTRL+C again. Does that work?

**Comment by megabyte6** [comment]
Yes, it works. Thank you! I completely forgot about using CTRL+C 🤦‍♂️.
