### ISSUE TITLE
Discord group for this project

### ISSUE THREAD

**Issue by NotJustPizza** [timvisee/lazymc#2]
This project seem really promising, it would be great to have Discord group to share and discuss ideas.

**Comment by timvisee** [comment]
Thanks for the suggestion.

I'm not an active Discord user, nor do I want to go through the trouble of managing a server at this moment for this side project. I hope that's understandable.

But, feel free to post any ideas or suggestions here! I've enabled the [discussion](https://github.com/timvisee/lazymc/discussions) board.
