### ISSUE TITLE
 Failed to serve status: ()

### ISSUE THREAD

**Issue by NereaCassian** [timvisee/lazymc#22]
Not an issue just asking why this happens.

Version: Forge 1.12.2
Plugins: None
Platform: ubuntu 20.4

the warn
`WARN  lazymc          > Failed to serve status: ()` 
appears  when the server is IDLE 

thanks in advance <3

**Comment by NereaCassian** [comment]
I solved it giving the public IP and the proxy ip of the server in te lazymc.toml

**Comment by timvisee** [comment]
Happy to see you were able to solve it. 👍

**Comment by NereaCassian** [comment]
My fix to the problem is right? just to know why rhw issue comes from exactly

**Comment by NereaCassian** [comment]
And sorry for bothering, but i also get this warn 
` lazymc::probe   > Failed to probe server, this may limit lazymc features`
all keeps working as intended, is something to worry about?
