### ISSUE TITLE
The server can't start

### ISSUE THREAD

**Issue by Wiiinterr** [timvisee/lazymc#25]
I just get this error
![billede_2022-07-08_151236254](https://user-images.githubusercontent.com/72213876/177998744-45798320-0a20-4a25-8139-622cf4c5fd54.png)

**Comment by timvisee** [comment]
This does not seem to be `lazymc` related, but an issue with the server itself.

Please make sure it runs fine without `lazymc` and resolve any issues that come up.

I'll close this because it seems unrelated to `lazymc`. Feel free to open this again if the issue remains.
