### ISSUE TITLE
Server start takes too long lazymc timesout

### ISSUE THREAD

**Issue by Nullvoid3771** [timvisee/lazymc#29]
Server start takes too long lazymc timesout, running direwolf20 and it has a lot of mods so server start takes awhile that lazymc times out and kills the server start.

Anyway to fix this? 

ERROR lazymc::montior > Force killing server, took too long to start or stop
 WARN  lazymc          > Server process stopped with error code (signal: 9)
 ERROR lazymc::montior > Force killing server, took too long to start or stop
 WARN  lazymc          > Failed to force kill server
 INFO  lazymc::monitor > Server is now sleeping

**Comment by timvisee** [comment]
You can set

```toml
[server]
start_timeout = 900
```

to a higher number. Please see:

https://github.com/timvisee/lazymc/blob/c6f860f01332d15481924e32d684b6f2f5b600b8/res/lazymc.toml#L50

**Comment by Nullvoid3771** [comment]
Thank you! Sorry I missed that configuration, but you definitely helped. Lazymc is exactly what I needed for my Minecraft server running off my nas. This game is ram hungry even when people aren’t in the server so having the ability to start the mc server only when needed is a big plus.

**Comment by timvisee** [comment]
Awesome to hear! Happy to see you find it useful. 😄
