### ISSUE TITLE
Seems like drop_banned_ips drops all connections

### ISSUE THREAD

**Issue by tW4r** [timvisee/lazymc#43]
Haven't tested this yet, but looking at the code, it seems like `[server] drop_banned_ips` config value just drops all connections instead of only banning the IP:

https://github.com/timvisee/lazymc/blob/be74e053f4380bb291cc62f5db4875c1f8ad297d/src/service/server.rs#L85-L90

**Comment by timvisee** [comment]
Woah! That's super bad. Good catch!

**Comment by timvisee** [comment]
Fixed by #44

**Comment by timvisee** [comment]
I've quickly released `v0.2.9` to get this out to the public as soon as possible.

It is releasing here: https://gitlab.com/timvisee/lazymc/-/pipelines/777105544

Thanks again.
