### ISSUE TITLE
LazyMC can't reach 1.20.1 server

### ISSUE THREAD

**Issue by kalmenn** [timvisee/lazymc#71]
Compiling from source on commit d058164 , lazymc correctly starts the server but fails to probe it / proxy player connections.
In game, it still shows as "server is starting" for as long as the timeout is in the config and then kills the process.

I've tried both fabric 1.20.1 and the vanilla 1.20.1 server. This doesn't happen with the 1.20.3 vanilla server: The server starts as expected and incoming connections successfully get proxied.

The same happened when I used the latest release build from github.

Rolling back to 485941c fixed the issue.

Is the new minimum supported minecraft version now 1.20.3 ? I couldn't figure out if that was the case from the documentation.

Thanks !

**Comment by L40P** [comment]
Observed the same behaviour running a fabric 1.20.1 server.
Rolled back lazymc to release version v0.2.10 and everything worked fine.

This is either an actual issue or the documentation on version compatibility isnt very clear.

**Comment by timvisee** [comment]
The latest version only supports Minecraft 1.20.3 and up, as stated in the README.
