### ISSUE TITLE
Server doesn't boot up.

### ISSUE THREAD

**Issue by tungthechicken** [timvisee/lazymc#80]
LazyMC couldn't start the server, showing an error code. Starting up the server manually, then join the game via LazyMC works fine. Even when everyone leaves the server, LazyMC was able to shutdown the server. What should I do in this case?
![Screenshot 2024-08-22 183211](https://github.com/user-attachments/assets/b17d0eb8-4b04-4262-bf88-913c89c5a9c2)

**Comment by timvisee** [comment]
The error in between is problematic. Are you sure you're using a functional server.jar and using the correct Java version?

It may help to give starting the server a try with the same command you specify in lazymc. Lazymc doesn't do anything special, other than just calling that command for you.

**Comment by tungthechicken** [comment]
Hello and thanks for the respone!
Using the default generated startup command from "lazymc.toml"
`java -Xmx1G -Xms1G -jar server.jar --nogui`
The server works fine.
![image](https://github.com/user-attachments/assets/1c1a3864-0c3f-472c-bdba-50235b388888)

I'm currently using Amazon Corretto Java 21 [](https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/downloads-list.html) and Vanilla Minecraft version 1.20.3. Same thing happened with PaperMC 1.20.4 with slightly different error code.
![image](https://github.com/user-attachments/assets/7d6cf484-3774-4af9-8686-ae559665d0c2)

**Comment by tungthechicken** [comment]
So after some tinkering around, I've found out that I just need to change `directory = "."` to `directory = "E:\\New folder"` in the lazymc.toml file. Sorry for wasting your precious time!
